# Generated by Django 3.2.5 on 2021-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tvshow_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.DateField(),
        ),
    ]
